<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE conversation
[
<!ELEMENT conversation (messasge+) >
<!ELEMENT message (username,msjtitle,msjcontent,datetime) >
<!ELEMENT username (#PCDATA) >
<!ELEMENT msjtitle (#PCDATA) >
<!ELEMENT msjcontent (#PCDATA) >
<!ELEMENT datetime (#PCDATA) >
<!ATTLIST messasge msjID CDATA #REQUIRED >
]>

<conversation>

<message msjID="0">
<username>Paul</username>
<msjtitle>Doctor_Appointment</msjtitle>
<msjcontent>Hello Angela,have you made an appoinment to dentist with that ache that was bothering you!</msjcontent>
<datetime>5/19/2021 12:13</datetime>
</message>

<message msjID="1">
<username>Angela</username>
<msjtitle>Doctor_Appointment_Response</msjtitle>
<msjcontent>Hi Paul,yes I've made an appoinment tomorrow!</msjcontent>
<datetime>5/19/2021 12:15</datetime>
</message>

<message msjID="2">
<username>Paul</username>
<msjtitle>Doctor_Appointment_Response_Back</msjtitle>
<msjcontent>Ok,I'm glad to hear that,let me know,how you feel,after!</msjcontent>
<datetime>5/19/2021 12:16</datetime>
</message>

</conversation>
